import Head from "next/head";
import Image from "next/image";
import { Sidebar } from "../components/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Area presentation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar/>

      <div className=" p-4 sm:ml-64 bg-gray-700">
        <div className="p-4 rounded-lg  border-gray-700">
          <div className="grid grid-cols-5 gap-4 mb-4">
            <div className="flex items-center justify-center rounded h-28">
              <Image
                width={100}
                height={100}
                alt=""
                src="/logo-inohub.jpg"
                className="max-h-full"
              />
            </div>
            <div className="col-span-4 rounded h-28 flex items-center">
              <p className="text-5xl text-white text-bold">
                CaP/ETS | Digital Talents Academy
              </p>
            </div>
          </div>
          <div className="flex items-center justify-center rounded">
            <Image
              width={1200}
              height={80}
              alt=""
              src="/galera.png"
              className=" rounded-xl"
            />
          </div>
        </div>
      </div>
    </>
  );
}
